# Step 1
FROM node:14 AS builder
# 작업 디렉터리 명시
WORKDIR /app
# 프로젝트의 모든 파일을 WORKDIR로 복사
COPY . .
# npm install과 build 진행
RUN npm install
RUN npm run build

# Step2
FROM node:14-alpine
WORKDIR /app
## Step 1의 builder에서 build된 프로젝트를 가져온다
COPY --from=builder /app ./
CMD ["npm", "run", "start"]